ARG GO_IMAGE=golang:1.23.12-bookworm
ARG RUNTIME_IMAGE=debian:bookworm-slim

FROM ${GO_IMAGE} AS driver-build
WORKDIR /src
ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG VERSION=v2.3.0
ARG GIT_COMMIT=unknown
ARG BUILD_DATE=unknown
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build \
    -ldflags "-X github.com/capitalonline/cds-csi-driver/pkg/common.version=${VERSION} -X github.com/capitalonline/cds-csi-driver/pkg/common.gitCommit=${GIT_COMMIT} -X github.com/capitalonline/cds-csi-driver/pkg/common.buildDate=${BUILD_DATE} -s -w" \
    -o /out/cds-csi-driver ./cmd/

FROM ${RUNTIME_IMAGE}
COPY --from=driver-build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
RUN sed -i 's|http://deb.debian.org|https://deb.debian.org|g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates util-linux && \
    rm -rf /var/lib/apt/lists/*
COPY --from=driver-build /out/cds-csi-driver /cds-csi-driver
ENTRYPOINT ["/cds-csi-driver"]
