bases:
  - ../../base

images:
  - name: registry-bj.capitalonline.net/cck/cds-csi-driver
    newName: harbor-dev.yun-paas.com/csi_agent/cds-csi-driver
    newTag: v2.1.5
  - name: registry-bj.capitalonline.net/cck/csi-provisioner
    newName: harbor-dev.yun-paas.com/csi_agent/csi-provisioner
    newTag: v1.5.0
  - name: registry-bj.capitalonline.net/cck/csi-livenessprobe
    newName: harbor-dev.yun-paas.com/csi_agent/csi-livenessprobe
    newTag: v2.0.0
  - name: registry-bj.capitalonline.net/cck/csi-node-driver-registrar
    newName: harbor-dev.yun-paas.com/csi_agent/csi-node-driver-registrar
    newTag: v1.2.0
