apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oss-csi-dynamic
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: oss-csi-dynamic
  resources:
    requests:
      storage: 1Gi
