apiVersion: v1
kind: Service
metadata:
  name: oss-csi-provisioner
  namespace: kube-system
  labels:
    name: oss-csi-provisioner
spec:
  selector:
    type: oss-csi-provisioner
  ports:
    - name: healthz
      port: 9808
