bases:
- ../../base

images:
- name: registry-bj.capitalonline.net/cck/cds-csi-driver-oss
  newName: harbor-dev.yun-paas.com/storage_image/cds-csi-driver-oss
  newTag: v2.2.1
- name: harbor-dev.yun-paas.com/csi_agent/csi-provisioner
  newName: harbor-dev.yun-paas.com/csi_agent/csi-provisioner
  newTag: v3.1.0
- name: registry-bj.capitalonline.net/cck/csi-livenessprobe
  newName: harbor-dev.yun-paas.com/csi_agent/csi-livenessprobe
  newTag: v2.0.0
- name: registry-bj.capitalonline.net/cck/csi-node-driver-registrar
  newName: harbor-dev.yun-paas.com/csi_agent/csi-node-driver-registrar
  newTag: v1.2.0
