apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-csi-csd-sc-subpath
# Must match the --driver argument of the installed NAS CSI controller.
provisioner: nas.csi.cds.net
parameters:
  volumeAs: subpath
  server: "replace-with-nfs-server"
  path: "/"
  vers: "4.0"
  options: noresvport
  archiveOnDelete: "true"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false
